config/routes.rb
Rails.application.routes.draw do
  root 'react#home'

  namespace :api do
    namespace :v1 do
      resources :menus, only: %i[show], param: :name
      resources :pages, only: %i[show], param: :slug
    end
  end

  namespace :admin do
    resources :pages
    resources :categories do
      resources :products, except: %i[index]
    end
    root 'pages#index'
  end

  get '*path', to: 'react#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend ActsAsTree::TreeWalker
  extend ActsAsTree::TreeView

  acts_as_list scope: :parent_id
  acts_as_tree order: 'position'

  has_many :children, class_name: 'Category', foreign_key: 'parent_id',
                      dependent: :destroy
  has_many :products, dependent: :destroy

  scope :root_categories, -> { where(parent_id: nil).order(:position) }

  def parents(node = self, node_parents = [])
    node_parents.tap do
      unless node.parent.nil?
        node_parents.push(node.parent)
        parents(node.parent, node_parents)
      end
    end
  end

  def full_name
    "#{name} - #{parents.map(&:name).join('-')}".parameterize
  end
end

app/models/concerns/sluggable.rb
class Sluggable < Module
  extend ActiveSupport::Concern

  def initialize(target)
    @target = target
  end

  def extended(_)
    target = @target
    define_method(:slug) do |resource, _|
      return unless resource[target]
      resource[target].parameterize
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
  acts_as_list

  scope :visible, -> { where(visible: true) }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  def pictures?
    pictures.any?
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    helper CategoriesPresenter

    def index; end

    def show; end

    def update
      category = Category.find(params[:id])
      category.update_attributes!(update_params)
      head :ok
    end

    def new
      @category_form = Category.new
    end

    def create
      @category_form = Category::CreateForm.new(create_params)
      response = Category::Create.call(form: @category_form)

      if response.success?
        flash[:success] = response.success_message
        redirect_to admin_categories_path
      else
        flash[:error] = response.error_message
        render :new
      end
    end

    def destroy
      category = Category.find(params[:id])
      response = Category::Destroy.call(resource: category)
      flash[:success] = response.success_message
      redirect_to admin_categories_path
    end

    private

    def update_params
      params.require(:category).permit(:parent_id, :position)
    end

    def create_params
      params.require(:category).permit(:name, :parent_id)
    end
  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < ApplicationController
    def index
      @pages = Page.all
    end

    def new
      @page_form = Page.new
    end

    def create
      @page_form = Page::CreateForm.new(create_params)
      response = Page::Create.call(form: @page_form)

      if response.success?
        flash[:success] = response.success_message
        redirect_to admin_root_path
      else
        flash[:error] = response.error_message
        render :new
      end
    end

    def edit
      @page = Page.find(params[:id])
    end

    def update
      @page = Page::UpdateForm.new(update_params)
      response = Page::Update.call(form: @page)

      if response.success?
        flash[:success] = response.success_message
        redirect_to admin_root_path, success: response.success_message
      else
        flash[:error] = response.error_message
        render :edit
      end
    end

    private

    def create_params
      params.require(:page).permit(:title, :body)
    end

    def update_params
      params.require(:page).permit(:title, :body, :slug, :visible, :id)
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :set_category, only: %i[edit new create update]
    before_action :set_product, only: %i[edit update]

    def new
      @product_form = Product.new
    end

    def create
      @product_form = Product::CreateForm.new(create_params)
      response = Product::Create.call(form: @product_form)

      if response.success?
        flash[:success] = response.success_message
        redirect_to admin_root_path
      else
        flash[:error] = response.error_message
        render :new
      end
    end

    def edit; end

    def update
      @product = Product::UpdateForm.new(update_params)
      response = Product::Update.call(form: @product)

      if response.success?
        flash[:success] = response.success_message
        redirect_to admin_root_path, success: response.success_message
      else
        flash[:error] = response.error_message
        render :edit
      end
    end

    private

    def create_params
      params.require(:product).permit(
        :name, :description, :quantity, :category_id, :visible, pictures: []
      ).merge(category_id: params[:category_id])
    end

    def update_params
      create_params.merge(slug: params[:product][:slug],
                          id: params[:product][:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

    def set_product
      @product = Product.find(params[:id])
    end
  end
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/api/v1/menus_controller.rb
module Api
  module V1
    class MenusController < ApplicationController
      def show
        @menu = Menu.fetch(name: params[:name])
      end
    end
  end
end

app/controllers/api/v1/pages_controller.rb
module Api
  module V1
    class PagesController < ApplicationController
      before_action :set_page, only: %i[show]

      def show; end

      private

      def set_page
        @page = Page.find_by(slug: params[:slug])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/react_controller.rb
class ReactController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-error'
    when 'alert' then 'alert alert-error'
    end
  end
end

app/helpers/tree_helper.rb
module TreeHelper
  def render_tree_view(nodes, response = '')
    nodes.each do |node|
      response += render_tree_item(node)
    end
    response.html_safe
  end

  def render_tree_item(node)
    render partial: 'admin/shared/tree_item', locals: { node: node }
  end

  def tree_select_box(nodes, select_options = [])
    select_options.tap do
      nodes.each do |node|
        select_options.push([node_name_with_level(node), node[:id]])
        unless node[:children].empty?
          tree_select_box(node[:children], select_options)
        end
      end
    end
  end

  private

  def node_name_with_level(node)
    '-' * (node[:level] + 1) + ' ' + node[:name]
  end
end

app/views/admin/categories/_form.html.slim
= form_for [:admin, category], html:{class: 'form-horizontal'} do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :parent_id, I18n.t('parent'), class: 'control-label col-lg-2'
    .col-lg-10
      = f.select :parent_id, tree_select_box(category_tree), class: 'form-control', include_blank: true
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit I18n.t("categories.save"), class: "btn btn-primary"

app/views/admin/categories/_products.html.slim
table.table.table-hover
  thead
    tr
     td = I18n.t('name')
     td = I18n.t('quantity')
     td = I18n.t('visibility')
     td = I18n.t('created_at')
     td = I18n.t('pictures')
  tbody
    - category.products.each do |product|
      = render product

app/views/admin/categories/index.html.slim
.content-header
  h2 = I18n.t("categories.categories")
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          h3.box-title
            = link_to I18n.t("categories.create"), new_admin_category_path , class: 'btn btn-primary btn-sm', data: { turbolinks: false }
        .box-body
          ol.sortable#categories
            = render_tree_view(categories)
javascript:
  $(document).ready(function(){
    $('ol.sortable').nestedSortable({
      forcePlaceholderSize: true,
      handle: 'div',
      helper: 'clone',
      items: 'li',
      opacity: .6,
      placeholder: 'placeholder',
      revert: 250,
      tabSize: 25,
      tolerance: 'pointer',
      toleranceElement: '> div',
      maxLevels: 4,
      isTree: true,
      expandOnHover: 700,
      startCollapsed: false,
      update: function( event, ui ) {
        var draggedItem = ui.item;
        var nodeId = draggedItem.data('node-id');
        var parendNodeId = draggedItem.parents('.mjs-nestedSortable-expanded')
                                      .data('node-id') || null;
        $.ajax({
          url: '/admin/categories/'+nodeId,
          method: 'PATCH',
          data: {
            category: {
              parent_id: parendNodeId,
              position: draggedItem.index()
            }
          }
        })
      }
    });
  });

app/views/admin/categories/new.html.slim
.row
  .col-lg-12
    .box
      .box-header
        h2
          = "| #{I18n.t('categories.new')}"
      .box-body
        = render partial: 'admin/categories/form', locals: { category: @category_form }

app/views/admin/categories/show.html.slim
.content-header
  h2 = "#{I18n.t('category')} | #{category.name}"
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          h3.box-title
            = link_to I18n.t('products.add'), new_admin_category_product_path(category), class: 'btn btn-sm btn-primary'
        .box-body
          - if category.products.any?
            = render partial: '/admin/categories/products'
          - else
            .container
              h2.jumbotron.text-center = I18n.t('categories.no_products')

app/views/admin/pages/_edit_fields.html.slim
.form-group
  = f.label :slug, class: 'control-label col-lg-2'
  .col-lg-10
    = f.text_field :slug, class: 'form-control'
.form-group
  = f.label :visible, class: 'control-label col-lg-2'
  .col-lg-10
    = f.check_box :visible
= f.hidden_field :id

app/views/admin/pages/_form.html.slim
= form_for [:admin, page], html:{class: 'form-horizontal'} do |f|
  .form-group
    = f.label :title, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control'
  - if page.persisted?
    = render partial: 'admin/pages/edit_fields', locals: { f: f, page: page }
  .form-group
    = f.label :body, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :body, class: 'form-control wysihtml5', rows: 20


  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit I18n.t("save"), class: "btn btn-primary"

app/views/admin/pages/edit.html.slim
.row
  .col-lg-12
    .box
      .box-header
        h2
          = "| #{I18n.t('pages.new')}"
      .box-body
        = render partial: 'admin/pages/form', locals: { page: @page }

app/views/admin/pages/index.html.slim
.content-header
  h2 = I18n.t("pages.pages")
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          h3.box-title
            = link_to I18n.t("pages.create"), new_admin_page_path , class: 'btn btn-primary btn-sm', data: { turbolinks: false }
        .box-body
          .table-responsive
            table.table.table-striped
              thead
                tr
                  th = I18n.t("title")
                  th = I18n.t("actions")
              tbody
                - @pages.each do |page|
                  tr
                    td = page.title
                    td
                      = link_to I18n.t("edit"), edit_admin_page_path(page), class: 'btn btn-success btn-sm', data: { turbolinks: false }
                      = "\s"
                      = link_to I18n.t("delete"), edit_admin_page_path(page), class: 'btn btn-danger btn-sm'

app/views/admin/pages/new.html.slim
.row
  .col-lg-12
    .box
      .box-header
        h2
          = "| #{I18n.t('pages.new')}"
      .box-body
        = render partial: 'admin/pages/form', locals: { page: @page_form }

app/views/admin/products/_edit_fields.html.slim
.form-group
  = f.label :slug, class: 'control-label col-lg-2'
  .col-lg-10
    = f.text_field :slug, class: 'form-control'
=f.hidden_field :id

app/views/admin/products/_form.html.slim
= form_for [:admin, category, product], html: {class: 'form-horizontal'} do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :quantity, class: 'control-label col-lg-2'
    .col-xs-1
      = f.number_field :quantity, class: 'form-control', min: "0"

  .form-group
    = f.label :visible, class: 'control-label col-lg-2'
    .col-lg-10
      = f.check_box :visible

  - if product.persisted?
    = render partial: '/admin/products/edit_fields', locals: { f: f }

  .form-group
    = f.label :pictures, class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :pictures, multiple: true

  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :description, class: 'form-control wysihtml5', rows: 20

  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit I18n.t("save"), class: "btn btn-primary"

app/views/admin/products/_product.html.slim
tr
  td = link_to product.name, edit_admin_category_product_path(category, product), data: { turbolinks: false }
  td = product.quantity
  td = product.visible
  td = product.created_at.strftime("%B %d, %Y")
  td
    -if product.pictures?
      = image_tag product.pictures.first.thumb.url
    -else
      p No Picture

app/views/admin/products/edit.html.slim
.content-header
  h2 = "#{I18n.t('product')} | #{@product.name}"
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          = render partial: '/admin/products/form', locals: { product: @product, category: @category }

app/views/admin/products/new.html.slim
.content-header
  h2 = "#{I18n.t('products.create')}"
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          = render partial: '/admin/products/form', locals: { product: @product_form, category: @category }

app/views/admin/shared/_tree_item.slim
li data-node-id==(node[:id])
  div.leaf-content
    p.header
      == node[:name]
    div.actions.btn-toolbar
      = link_to I18n.t('show'), admin_category_path(node[:id]), class: 'btn btn-default btn-sm'
      = link_to I18n.t('delete'), admin_category_path(node[:id]), method: :delete, data: { confirm: I18n.t('confirmation') }, class: 'btn btn-danger btn-sm'
  - unless node[:children].empty?
    ol
      - node[:children].each do |child_node|
        = render partial: 'admin/shared/tree_item', locals: { node: child_node }

app/views/layouts/admin/application.html.slim
doctype HTML
HTML
  head
    = render 'layouts/admin/shared/header'
  
  body.fixed.skin-red
    .wrapper
      = render 'layouts/admin/navigation/layout'
      .content-wrapper
        = render 'layouts/admin/shared/flash'
        = yield

app/views/layouts/admin/navigation/_footer.slim
footer.main-footer
  .pull-right.hidden-xs
    | Anything you want
  strong
    | Copyright © 2016
    a href="#" Company
  | All rights reserved.

app/views/layouts/admin/navigation/_header.slim
header.main-header
  = link_to I18n.t("administration"), admin_root_path, class: 'logo' 
  /! Header Navbar: style can be found in header.less
  nav.navbar.navbar-static-top role="navigation"

app/views/layouts/admin/navigation/_layout.slim
= render 'layouts/admin/navigation/header'
= render 'layouts/admin/navigation/sidebar'

app/views/layouts/admin/navigation/_sidebar.slim
.main-sidebar
  .sidebar
    .user-panel
      .pull-left.image
        img.img-circle alt=("User Image") src="http://placehold.it/160x160" /
      .pull-left.info
        p User Name
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    ul.sidebar-menu
      li
        = link_to I18n.t('pages.pages'), admin_pages_path
      li
        = link_to I18n.t('categories.categories'), admin_categories_path

app/views/layouts/admin/shared/_flash.slim
- flash.each do |key, value|
    div class=(flash_class(key))
      = value

app/views/layouts/admin/shared/_header.slim
title Admin
= csrf_meta_tags
= action_cable_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload'
= stylesheet_link_tag href=\
"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/react/home.html.erb
<%= javascript_pack_tag 'application' %>